CREATE DATABASE doings
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE doings;

CREATE TABLE projects (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  category VARCHAR(100) NOT NULL,
  user_id INT NOT NULL
);

CREATE TABLE tasks (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  user_id INT NOT NULL,
  project_id INT NOT NULL,
  first_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ready_or_not INT DEFAULT 0,
  task VARCHAR(100) NOT NULL,
  evidence VARCHAR(100),
  final_date TIMESTAMP
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(300) NOT NULL UNIQUE,
  user_name VARCHAR(300) NOT NULL,
  parole VARCHAR(600) NOT NULL
);
